"""
Builds/refreshes File_Manifest.xlsx at the project root — a running log of every
file committed to Ben's synced folder, with a description and last-updated timestamp.
Re-run this (with updated FILES list) any time files are added or edited.
"""
import os
import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter

PROJECT_ROOT = os.path.expanduser("~/Documents/kinetic-project")  # working git clone lives here now (see CHANGELOG 2026-09-28)
OUTPUT_PATH = os.path.join(PROJECT_ROOT, "File_Manifest.xlsx")

# (relative file path, category, description)
FILES = [
    ("README.md", "Docs", "Project overview and folder structure guide"),
    ("CHANGELOG.md", "Docs", "Plain-English log of every decision and build step"),
    ("docs/business_context.md", "Docs", "Kinetic business model: subscriptions, courses, merch, seasonality"),
    ("docs/schema_reference.md", "Docs", "Full 47-table schema reference across all domains"),
    ("docs/generation_plan.md", "Docs", "Build sequence, validation approach, canonical metrics, locked conventions"),
    ("generator/params.py", "Code", "Phase 0 Step 1: global constants (scale, dates, pricing, rates)"),
    ("generator/build_calendar.py", "Code", "Phase 0 Steps 2-3: builds seasonality calendar + channel mix schedule"),
    ("generator/build_manifest.py", "Code", "Builds/refreshes this file manifest spreadsheet"),
    ("internal/_sim_seasonality_calendar.csv", "Internal artifact", "Weekly demand multiplier driving signups/spend/traffic"),
    ("internal/_sim_channel_mix_schedule.csv", "Internal artifact", "Acquisition channel share over time (Meta/Google/YouTube/DV360/Snap/TikTok/organic)"),
    ("internal/seasonality_preview.png", "Chart", "Visual sanity-check of the seasonality calendar"),
    (".gitignore", "Repo config", "Excludes Python __pycache__ from git/sync"),
    ("File_Manifest.xlsx", "Docs", "This file — running log of every file committed to the folder"),
    ("generator/sim_utils.py", "Code", "Shared weighted date/channel sampling helpers"),
    ("generator/build_anonymous_population.py", "Code", "Phase 0 Step 4: builds the ~2,000-person anonymous ghost population (anon_id now hash-derived, not uuid4 -- reproducibility fix)"),
    ("generator/simulate_customers.py", "Code", "Phase 0 Steps 5-6: per-customer master timeline + attribution ground truth (fixed: course_merch_only orders now reconciled against the eventual subscription window; pre_signup_anon_id now hash-derived, not uuid4)"),
    ("internal/_sim_anonymous_population.csv", "Internal artifact", "Anonymous visitors who never become tracked customers; source of guest merch orders"),
    ("internal/_sim_customer_timeline.json", "Internal artifact", "Full nested ground-truth simulation for all 100 customers (signup, trial, subscriptions, orders, churn)"),
    ("internal/_sim_customer_timeline_summary.csv", "Internal artifact", "Flattened, spreadsheet-readable summary of the customer timeline"),
    ("internal/_sim_attribution_ground_truth.json", "Internal artifact", "True acquisition/reactivation channel per customer, kept separate from intentionally messy shipped UTM data"),
    ("generator/build_simulation_charts.py", "Code", "Builds the funnel + segment breakdown charts for the simulation analysis"),
    ("internal/funnel_chart.png", "Chart", "Customer funnel: total -> trial started -> converted -> active today"),
    ("internal/segment_breakdown_chart.png", "Chart", "Part-to-whole breakdown of all customers' current status"),
    ("docs/phase0_simulation_analysis.md", "Docs", "Summary analysis of the recalibrated Phase 0 simulation results"),
    ("generator/build_products.py", "Code", "Phase 1: builds the products table (~12-item course/merch catalog)"),
    ("generator/validate_products.py", "Code", "Phase 1: 5-layer validation for products (structural/referential/temporal/business-rule/distributional)"),
    ("data/products.csv", "Shipped table", "Phase 1: products table (course + merch catalog)"),
    ("generator/build_product_variants.py", "Code", "Phase 1: builds product_variants (sizes for apparel, single variant elsewhere)"),
    ("generator/validate_product_variants.py", "Code", "Phase 1: 5-layer validation for product_variants, including FK to products"),
    ("data/product_variants.csv", "Shipped table", "Phase 1: product_variants table (21 variants across 12 products)"),
    ("generator/build_subscription_plans.py", "Code", "Phase 1: builds subscription_plans (Basic/Plus x monthly/annual)"),
    ("generator/validate_subscription_plans.py", "Code", "Phase 1: 5-layer validation for subscription_plans"),
    ("data/subscription_plans.csv", "Shipped table", "Phase 1: subscription_plans table (4 plans)"),
    ("generator/build_customers.py", "Code", "Phase 1: builds customers table from the master timeline; defines customer_id mapping"),
    ("generator/validate_customers.py", "Code", "Phase 1: 5-layer validation for customers, incl. 1:1 reconciliation vs. the timeline"),
    ("data/customers.csv", "Shipped table", "Phase 1: customers table (860 rows, one per simulated customer)"),
    ("generator/build_customer_addresses.py", "Code", "Phase 1: builds customer_addresses (billing/shipping, obviously-fake streets)"),
    ("generator/validate_customer_addresses.py", "Code", "Phase 1: 5-layer validation for customer_addresses"),
    ("data/customer_addresses.csv", "Shipped table", "Phase 1: customer_addresses table (1,431 rows)"),
    ("generator/build_devices.py", "Code", "Phase 1: builds devices (customer + anonymous-ghost devices; 2nd-device anon_id now hash-derived, not uuid4)"),
    ("generator/validate_devices.py", "Code", "Phase 1: 5-layer validation for devices"),
    ("data/devices.csv", "Shipped table", "Phase 1: devices table (18,042 rows: known-customer + ghost devices)"),
    ("generator/build_identity_map.py", "Code", "Phase 1: builds identity_map (anonymous_id -> customer_id resolution events)"),
    ("generator/validate_identity_map.py", "Code", "Phase 1: 5-layer validation for identity_map"),
    ("data/identity_map.csv", "Shipped table", "Phase 1: identity_map table (992 rows)"),
    ("generator/build_segments.py", "Code", "Phase 1: builds segments (27 definitions: 9 customer-grain, 18 anonymous -- 3 audience concepts x 6 ad platforms)"),
    ("generator/validate_segments.py", "Code", "Phase 1: 5-layer validation for segments"),
    ("data/segments.csv", "Shipped table", "Phase 1: segments table (27 rows) -- completes Phase 1 (all 8 tables)"),
    ("generator/build_subscriptions.py", "Code", "Phase 2: builds subscriptions (Stripe-shaped subscription objects; assigns billing_interval + next-renewal date, resolving the long-flagged Phase 2 gap)"),
    ("generator/validate_subscriptions.py", "Code", "Phase 2: 5-layer validation for subscriptions"),
    ("data/subscriptions.csv", "Shipped table", "Phase 2: subscriptions table (576 rows: one Stripe-shaped subscription object per trial-or-interval)"),
    ("generator/build_subscription_events.py", "Code", "Phase 2: builds subscription_events (event log behind every subscription: trial_started/converted/expired, renewed, upgraded/downgraded, payment_failed, canceled, resumed)"),
    ("generator/validate_subscription_events.py", "Code", "Phase 2: 5-layer validation for subscription_events"),
    ("data/subscription_events.csv", "Shipped table", "Phase 2: subscription_events table (2,423 rows, incl. ~3% deliberate duplicate webhook-style rows)"),
    ("generator/build_invoices.py", "Code", "Phase 2: builds invoices (one per initial charge + renewal, plus uncollectible/open for failed payments) -- completes Phase 2 (all 3 tables)"),
    ("generator/validate_invoices.py", "Code", "Phase 2: 5-layer validation for invoices"),
    ("data/invoices.csv", "Shipped table", "Phase 2: invoices table (1,229 rows) -- completes Phase 2"),
    ("generator/build_discount_codes.py", "Code", "Phase 3: builds discount_codes (hand-curated list: evergreen + seasonal promo codes) -- built first in Phase 3 since orders needs it"),
    ("generator/validate_discount_codes.py", "Code", "Phase 3: 5-layer validation for discount_codes"),
    ("data/discount_codes.csv", "Shipped table", "Phase 3: discount_codes table (7 rows)"),
    ("generator/build_orders.py", "Code", "Phase 3: builds orders (customer course/merch + guest merch), cross-validated against subscriptions.csv"),
    ("generator/validate_orders.py", "Code", "Phase 3: 5-layer validation for orders, incl. the no-course-during-subscription cross-check"),
    ("data/orders.csv", "Shipped table", "Phase 3: orders table (3,650 rows: 1,061 course + 1,332 customer-merch + 1,257 guest-merch)"),
    ("generator/build_order_line_items.py", "Code", "Phase 3: builds order_line_items (one row per order -- resolves each order's price tier down to a specific product + variant)"),
    ("generator/validate_order_line_items.py", "Code", "Phase 3: 5-layer validation for order_line_items"),
    ("data/order_line_items.csv", "Shipped table", "Phase 3: order_line_items table (3,650 rows, one per order)"),
    ("generator/build_payments.py", "Code", "Phase 3: builds payments (one Stripe-shaped Charge attempt per row; models realistic declined-then-retried charge attempts)"),
    ("generator/validate_payments.py", "Code", "Phase 3: 5-layer validation for payments"),
    ("data/payments.csv", "Shipped table", "Phase 3: payments table (3,964 rows: 3,650 succeeded + 314 failed retry attempts)"),
    ("generator/build_refunds.py", "Code", "Phase 3: builds refunds (against a small share of orders' succeeded payments) -- completes Phase 3 (all 5 tables)"),
    ("generator/validate_refunds.py", "Code", "Phase 3: 5-layer validation for refunds"),
    ("data/refunds.csv", "Shipped table", "Phase 3: refunds table (159 rows, 4.4% of orders) -- completes Phase 3"),
    ("generator/build_customer_segment_membership.py", "Code", "Phase 4: builds customer_segment_membership (effective-dated, derived entirely from subscriptions/orders/invoices -- seg_009 skipped, needs Phase 5) -- completes Phase 4"),
    ("generator/validate_customer_segment_membership.py", "Code", "Phase 4: 5-layer validation for customer_segment_membership"),
    ("data/customer_segment_membership.csv", "Shipped table", "Phase 4: customer_segment_membership table (2,234 rows across 8 of 9 customer-grain segments) -- completes Phase 4"),
    ("generator/build_web_sessions.py", "Code", "Phase 5: builds web_sessions (marketing-site browsing; known customers + anonymous ghosts, engagement_tier-driven volume)"),
    ("generator/validate_web_sessions.py", "Code", "Phase 5: 5-layer validation for web_sessions"),
    ("data/web_sessions.csv", "Shipped table", "Phase 5: web_sessions table (30,285 rows: 6,476 identity-resolved + 23,809 anonymous)"),
    ("generator/build_web_events.py", "Code", "Phase 5: builds web_events (page_view/product_view/add_to_cart/begin_checkout/purchase/search; every order gets exactly one purchase event)"),
    ("generator/validate_web_events.py", "Code", "Phase 5: 5-layer validation for web_events"),
    ("data/web_events.csv", "Shipped table", "Phase 5: web_events table (117,706 rows)"),
    ("generator/build_app_sessions.py", "Code", "Phase 5: builds app_sessions (in-app fitness usage, driven by real subscription intervals + course orders, keyed off engagement_tier)"),
    ("generator/validate_app_sessions.py", "Code", "Phase 5: 5-layer validation for app_sessions"),
    ("data/app_sessions.csv", "Shipped table", "Phase 5: app_sessions table (19,610 rows across 496 customers)"),
    ("generator/build_app_events.py", "Code", "Phase 5: builds app_events (class_started/workout_completed/workout_abandoned/streak_achieved -- streaks derived from real consecutive session dates) -- completes Phase 5"),
    ("generator/validate_app_events.py", "Code", "Phase 5: 5-layer validation for app_events"),
    ("data/app_events.csv", "Shipped table", "Phase 5: app_events table (39,370 rows) -- completes Phase 5"),
    ("generator/build_braze_email_campaigns.py", "Code", "Phase 6: builds braze_email_campaigns (hand-curated: 7 triggered + 2 broadcast) -- built first, events table needs it"),
    ("generator/validate_braze_email_campaigns.py", "Code", "Phase 6: 5-layer validation for braze_email_campaigns"),
    ("data/braze_email_campaigns.csv", "Shipped table", "Phase 6: braze_email_campaigns table (9 rows)"),
    ("generator/build_web_events.py", "Code", "Phase 5: builds web_events (retroactive fix: timestamp offsets now rounded to whole seconds, fixing a latent fractional-second formatting bug across all 117,706 rows)"),
    ("data/web_events.csv", "Shipped table", "Phase 5: web_events table (117,706 rows; retroactively rebuilt for the whole-second timestamp fix, same counts/logic)"),
    ("generator/build_braze_email_events.py", "Code", "Phase 6: builds braze_email_events (Send/Open/Click/Bounce/Unsubscribe funnel, derived from real trial/payment-failure/order/cart/reactivation sources)"),
    ("generator/validate_braze_email_events.py", "Code", "Phase 6: 5-layer validation for braze_email_events"),
    ("data/braze_email_events.csv", "Shipped table", "Phase 6: braze_email_events table (26,335 rows, 18,187 sends) -- updated 2026-08-13 by the cross-dataset audit's Check 6 fix (merch_to_sub_trigger send time-of-day)"),
    ("generator/build_braze_push_campaigns.py", "Code", "Phase 6: builds braze_push_campaigns (hand-curated: 5 triggered + 2 broadcast, push-appropriate subset) -- built before events table needs it"),
    ("generator/validate_braze_push_campaigns.py", "Code", "Phase 6: 5-layer validation for braze_push_campaigns"),
    ("data/braze_push_campaigns.csv", "Shipped table", "Phase 6: braze_push_campaigns table (7 rows)"),
    ("generator/build_braze_push_events.py", "Code", "Phase 6: builds braze_push_events (Send/Open/Click/Bounce/Unsubscribe funnel, gated on push_opt_in as a hard delivery precondition) -- completes Phase 6 (all 4 tables)"),
    ("generator/validate_braze_push_events.py", "Code", "Phase 6: 5-layer validation for braze_push_events"),
    ("data/braze_push_events.csv", "Shipped table", "Phase 6: braze_push_events table (9,897 rows, 7,851 sends) -- completes Phase 6 (25 of 47 tables shipped; Phase 7 paid media remains)"),
    ("generator/paid_media_common.py", "Code", "Phase 7: shared helpers used by all 6 platforms' daily performance tables -- maps any date to the seasonality calendar/channel-mix week and draws each day's per-channel spend baseline"),
    ("generator/build_meta_campaigns.py", "Code", "Phase 7 (Meta 1/4): builds meta_campaigns (4 evergreen objective campaigns + 3 flighted brand_lift campaigns timed near BFCM)"),
    ("generator/validate_meta_campaigns.py", "Code", "Phase 7: 5-layer validation for meta_campaigns"),
    ("data/meta_campaigns.csv", "Shipped table", "Phase 7 (Meta 1/4): meta_campaigns table (7 rows)"),
    ("generator/build_meta_ads.py", "Code", "Phase 7 (Meta 2/4): builds meta_ads (functions as the ad-set-level entity -- targeting_segment_id for retargeting/lookalike only)"),
    ("generator/validate_meta_ads.py", "Code", "Phase 7: 5-layer validation for meta_ads"),
    ("data/meta_ads.csv", "Shipped table", "Phase 7 (Meta 2/4): meta_ads table (10 rows)"),
    ("generator/build_meta_ad_insights_daily.py", "Code", "Phase 7 (Meta 3/4): builds meta_ad_insights_daily (spend/impressions/clicks driven by the shared seasonality calendar + channel-mix schedule)"),
    ("generator/validate_meta_ad_insights_daily.py", "Code", "Phase 7: 5-layer validation for meta_ad_insights_daily, incl. weekly-spend-vs-web_sessions correlation check"),
    ("data/meta_ad_insights_daily.csv", "Shipped table", "Phase 7 (Meta 3/4): meta_ad_insights_daily table (7,396 rows)"),
    ("generator/build_meta_ad_actions_daily.py", "Code", "Phase 7 (Meta 4/4): builds meta_ad_actions_daily (normalized actions array, derived directly from meta_ad_insights_daily.csv's own clicks) -- completes Meta (1 of 6 platforms)"),
    ("generator/validate_meta_ad_actions_daily.py", "Code", "Phase 7: 5-layer validation for meta_ad_actions_daily"),
    ("data/meta_ad_actions_daily.csv", "Shipped table", "Phase 7 (Meta 4/4): meta_ad_actions_daily table (35,504 rows) -- completes Meta"),
    ("generator/build_google_search_campaigns.py", "Code", "Phase 7 (Google Search 1/4): builds google_search_campaigns (5 evergreen objective campaigns, incl. an always-on brand-term defense campaign)"),
    ("generator/validate_google_search_campaigns.py", "Code", "Phase 7: 5-layer validation for google_search_campaigns"),
    ("data/google_search_campaigns.csv", "Shipped table", "Phase 7 (Google Search 1/4): google_search_campaigns table (5 rows)"),
    ("generator/build_google_search_ad_groups.py", "Code", "Phase 7 (Google Search 2/4): builds google_search_ad_groups (targeting_segment_id for RLSA retargeting/similar-audience lookalike only)"),
    ("generator/validate_google_search_ad_groups.py", "Code", "Phase 7: 5-layer validation for google_search_ad_groups"),
    ("data/google_search_ad_groups.csv", "Shipped table", "Phase 7 (Google Search 2/4): google_search_ad_groups table (8 rows)"),
    ("generator/build_google_search_keyword_performance_daily.py", "Code", "Phase 7 (Google Search 4/4 by build order): builds google_search_keyword_performance_daily -- the granular ground truth google_search_performance_daily aggregates from"),
    ("generator/validate_google_search_keyword_performance_daily.py", "Code", "Phase 7: 5-layer validation for google_search_keyword_performance_daily, incl. weekly-spend-vs-web_sessions correlation check"),
    ("data/google_search_keyword_performance_daily.csv", "Shipped table", "Phase 7 (Google Search 4/4 by build order): google_search_keyword_performance_daily table (19,932 rows)"),
    ("generator/build_google_search_performance_daily.py", "Code", "Phase 7 (Google Search 3/4 by schema order): builds google_search_performance_daily, aggregated exactly from keyword_performance_daily.csv up to ad_group/day grain -- completes Google Search (2 of 6 platforms)"),
    ("generator/validate_google_search_performance_daily.py", "Code", "Phase 7: 5-layer validation for google_search_performance_daily, incl. exact-sum reconciliation against keyword_performance_daily.csv"),
    ("data/google_search_performance_daily.csv", "Shipped table", "Phase 7 (Google Search 3/4 by schema order): google_search_performance_daily table (8,751 rows) -- completes Google Search"),
    ("generator/build_youtube_campaigns.py", "Code", "Phase 7 (YouTube 1/3): builds youtube_campaigns (4 evergreen objective campaigns + 3 flighted brand_lift campaigns, mirroring Meta's structure since YouTube Brand Lift is a real flighted measurement product)"),
    ("generator/validate_youtube_campaigns.py", "Code", "Phase 7: 5-layer validation for youtube_campaigns"),
    ("data/youtube_campaigns.csv", "Shipped table", "Phase 7 (YouTube 1/3): youtube_campaigns table (7 rows)"),
    ("generator/build_youtube_ad_groups.py", "Code", "Phase 7 (YouTube 2/3): builds youtube_ad_groups (targeting_segment_id for retargeting/lookalike only)"),
    ("generator/validate_youtube_ad_groups.py", "Code", "Phase 7: 5-layer validation for youtube_ad_groups"),
    ("data/youtube_ad_groups.csv", "Shipped table", "Phase 7 (YouTube 2/3): youtube_ad_groups table (9 rows)"),
    ("generator/build_youtube_performance_daily.py", "Code", "Phase 7 (YouTube 3/3): builds youtube_performance_daily (video_views/video_view_rate/average_cpv, spend-driven by the shared seasonality calendar + channel-mix schedule) -- completes YouTube (3 of 6 platforms)"),
    ("generator/validate_youtube_performance_daily.py", "Code", "Phase 7: 5-layer validation for youtube_performance_daily, incl. weekly-spend-vs-web_sessions correlation check"),
    ("data/youtube_performance_daily.csv", "Shipped table", "Phase 7 (YouTube 3/3): youtube_performance_daily table (6,394 rows) -- completes YouTube"),
    ("generator/build_dv360_insertion_orders.py", "Code", "Phase 7 (DV360 1/3): builds dv360_insertion_orders (5 evergreen objective IOs, incl. a VIEWABLE_CPM awareness IO)"),
    ("generator/validate_dv360_insertion_orders.py", "Code", "Phase 7: 5-layer validation for dv360_insertion_orders"),
    ("data/dv360_insertion_orders.csv", "Shipped table", "Phase 7 (DV360 1/3): dv360_insertion_orders table (5 rows)"),
    ("generator/build_dv360_line_items.py", "Code", "Phase 7 (DV360 2/3): builds dv360_line_items (targeting_segment_id for retargeting/lookalike only; brand_lift IO's line item is VIDEO type)"),
    ("generator/validate_dv360_line_items.py", "Code", "Phase 7: 5-layer validation for dv360_line_items"),
    ("data/dv360_line_items.csv", "Shipped table", "Phase 7 (DV360 2/3): dv360_line_items table (6 rows)"),
    ("generator/build_dv360_performance_daily.py", "Code", "Phase 7 (DV360 3/3): builds dv360_performance_daily -- fragments each line_item/day into several (exchange, environment) rows, DV360's genuinely different real-time-bidding schema shape -- completes DV360 (4 of 6 platforms)"),
    ("generator/validate_dv360_performance_daily.py", "Code", "Phase 7: 5-layer validation for dv360_performance_daily, incl. weekly-spend-vs-web_sessions correlation check and CONNECTED_TV-only-on-video-line-item check"),
    ("data/dv360_performance_daily.csv", "Shipped table", "Phase 7 (DV360 3/3): dv360_performance_daily table (25,776 rows) -- completes DV360"),
    ("generator/build_snap_campaigns.py", "Code", "Phase 7 (Snap 1/4): builds snap_campaigns (4 evergreen objective campaigns + 3 flighted brand_lift campaigns, flight budgets calibrated to avoid YouTube's earlier scale bug)"),
    ("generator/validate_snap_campaigns.py", "Code", "Phase 7: 5-layer validation for snap_campaigns"),
    ("data/snap_campaigns.csv", "Shipped table", "Phase 7 (Snap 1/4): snap_campaigns table (7 rows)"),
    ("generator/build_snap_ad_squads.py", "Code", "Phase 7 (Snap 2/4): builds snap_ad_squads (Snap's own real ad-set-level targeting entity, unlike Meta -- targeting_segment_id for retargeting/lookalike only)"),
    ("generator/validate_snap_ad_squads.py", "Code", "Phase 7: 5-layer validation for snap_ad_squads"),
    ("data/snap_ad_squads.csv", "Shipped table", "Phase 7 (Snap 2/4): snap_ad_squads table (8 rows)"),
    ("generator/build_snap_ads.py", "Code", "Phase 7 (Snap 3/4): builds snap_ads (creative-level entity, no targeting -- that lives on the ad squad)"),
    ("generator/validate_snap_ads.py", "Code", "Phase 7: 5-layer validation for snap_ads"),
    ("data/snap_ads.csv", "Shipped table", "Phase 7 (Snap 3/4): snap_ads table (10 rows)"),
    ("generator/build_snap_stats_daily.py", "Code", "Phase 7 (Snap 4/4): builds snap_stats_daily (spend in Snap's own micro-currency unit, swipes as the click-equivalent) -- completes Snap (5 of 6 platforms)"),
    ("generator/validate_snap_stats_daily.py", "Code", "Phase 7: 5-layer validation for snap_stats_daily, incl. weekly-spend-vs-web_sessions correlation check"),
    ("data/snap_stats_daily.csv", "Shipped table", "Phase 7 (Snap 4/4): snap_stats_daily table (7,407 rows) -- completes Snap"),
    ("generator/build_tiktok_campaigns.py", "Code", "Phase 7 (TikTok 1/4): builds tiktok_campaigns (4 evergreen objective campaigns + 3 flighted brand_lift campaigns)"),
    ("generator/validate_tiktok_campaigns.py", "Code", "Phase 7: 5-layer validation for tiktok_campaigns"),
    ("data/tiktok_campaigns.csv", "Shipped table", "Phase 7 (TikTok 1/4): tiktok_campaigns table (7 rows)"),
    ("generator/build_tiktok_adgroups.py", "Code", "Phase 7 (TikTok 2/4): builds tiktok_adgroups (TikTok's own real ad-set-level targeting entity -- targeting_segment_id for retargeting/lookalike only)"),
    ("generator/validate_tiktok_adgroups.py", "Code", "Phase 7: 5-layer validation for tiktok_adgroups"),
    ("data/tiktok_adgroups.csv", "Shipped table", "Phase 7 (TikTok 2/4): tiktok_adgroups table (8 rows)"),
    ("generator/build_tiktok_ads.py", "Code", "Phase 7 (TikTok 3/4): builds tiktok_ads (creative-level entity, no targeting -- that lives on the ad group)"),
    ("generator/validate_tiktok_ads.py", "Code", "Phase 7: 5-layer validation for tiktok_ads"),
    ("data/tiktok_ads.csv", "Shipped table", "Phase 7 (TikTok 3/4): tiktok_ads table (10 rows)"),
    ("generator/build_tiktok_reports_daily.py", "Code", "Phase 7 (TikTok 4/4): builds tiktok_reports_daily (spend/impressions/video_views, TikTok's always-video ad format) -- completes TikTok (6 of 6 platforms) AND all 47 tables"),
    ("generator/validate_tiktok_reports_daily.py", "Code", "Phase 7: 5-layer validation for tiktok_reports_daily, incl. weekly-spend-vs-web_sessions correlation check"),
    ("data/tiktok_reports_daily.csv", "Shipped table", "Phase 7 (TikTok 4/4): tiktok_reports_daily table (7,416 rows) -- completes TikTok, Phase 7, and the full 47-table dataset"),
    ("generator/audit_cross_dataset_alignment.py", "Code", "Post-completion cross-dataset alignment audit -- NOT a shipped-table script. 7 checks: aggregate spend vs. demand, channel mix vs. schedule, calendar-event alignment, long-run growth trend, renewal/lag structure, day-of-week/hour-of-day, timezone/precision sweep. Found and fixed a real bug (Check 6 -- merch_to_sub_trigger Braze sends all landing at exactly midnight); Checks 3 and 5 surfaced genuine, documented (non-bug) characteristics."),
    ("docs/cross_dataset_alignment_audit.md", "Docs", "Write-up of the 7-check cross-dataset alignment audit's results, including the merch_to_sub_trigger bug fix and the two documented (non-bug) findings from Checks 3 and 5"),
    ("warehouse/load_to_motherduck.py", "Code", "Post-dataset-completion tooling -- loads all 47 CSVs into a free MotherDuck (hosted DuckDB) database, one table per CSV, with a row-count verification per table. Run on the user's own machine, not inside the Cowork cloud sandbox (MotherDuck needs outbound internet the sandbox doesn't have). Reads its motherduck_token from either a shell env var or an optional warehouse/.env file (gitignored -- NOT tracked or synced by this manifest, since it holds a live credential). Confirmed working end-to-end against the user's own MotherDuck account (47/47 tables, exact row-count match)."),
    ("warehouse/analysis_queries.sql", "Code", "6 starter SQL queries against the kinetic MotherDuck database: monthly paid media spend by partner, directly attributed revenue by paid/owned channel, active subscribers by month, non-subscription revenue by month, monthly churn rate, top 5 grossing products per year. Heavily commented to explain modeling choices (e.g. the paid/owned attribution methodology split between storefront orders and subscription invoices)."),
    ("warehouse/query1_paid_media_spend.html", "Deliverable", "One-off interactive chart visualizing Query 1's actual output (pasted by the user from their own MotherDuck run): monthly paid media spend by partner, Aug 2023-Jul 2026. Multi-line chart with hover tooltip, legend isolate-toggle, dark mode, and a table view -- built per the dataviz skill (validated categorical palette, accessible contrast handling)."),
    ("warehouse/kinetic_dive.tsx", "Deliverable", "Source for the 'Kinetic -- Marketing & Revenue Overview' MotherDuck Dive -- a live, hosted interactive dashboard (React/Recharts), now organized as 5 tabs. Overview tab: the original 6 starter queries + KPI row. CEO tab: revenue growth/net-new-vs-churned subscribers/CAC payback, revenue mix (subscription vs. course vs. merch). CMO tab: acquisition funnel by channel (sessions -> trial starts -> conversions), retention/app engagement by acquisition channel. CFO tab: CAC and LTV:CAC by acquisition cohort, discount code cost + failed-payment recovery rate + a documented net-margin proxy (no COGS data exists for a true gross margin). Performance Marketing tab: campaign-level spend and platform-self-reported efficiency across all 38 real campaigns (sorted worst-CAC-first), CTR/CVR by platform and ad format. Each new section documents its modeling limits explicitly (e.g. platform-reported vs. site-attributed conversions have no shared join key in this dataset). Re-runs live SQL against the kinetic database on every open. Saved to MotherDuck via the MCP tools; this file is the local source-of-truth copy for sync/history. Live at https://app.motherduck.com/dives/kinetic-marketing-revenue-overview-58909b4e-d301-4794-bb59-ce46f9dc73a6 (dive_id 58909b4e-d301-4794-bb59-ce46f9dc73a6, version 2)."),
    ("README.md", "Docs", "Updated 2026-09-28: real project status (47/47 tables built+validated, live in MotherDuck) + direct link to the live Dive dashboard, replacing the stale 'planning complete, next step Phase 0' placeholder text"),
    ("docs/cross_dataset_alignment_audit.md", "Docs", "Updated 2026-09-28: closed the one open item (brand_lift/holiday-discount-code asymmetry across the 3 Novembers) -- reviewed and confirmed intentional, no data changed"),
    ("dbt/dbt_project.yml", "Code", "dbt project config for the new semantic layer -- staging views, intermediate views, mart tables"),
    ("dbt/profiles.yml", "Code", "dbt connection profile (MotherDuck md:kinetic, schema dbt_dev); no secrets"),
    ("dbt/.gitignore", "Repo config", "Excludes dbt's target/, dbt_packages/, logs/ from git"),
    ("dbt/README.md", "Docs", "How to install dbt-core + dbt-duckdb and run this project locally against MotherDuck (neither of Claude's environments can reach motherduck.com directly, so dbt run/test must be executed on the user's own machine)"),
    ("dbt/models/staging/kinetic/_kinetic__sources.yml", "Code", "Declares all 47 raw kinetic tables as dbt sources, so every staging model references source() rather than a hardcoded table name"),
    ("dbt/models/staging/kinetic/stg_kinetic__customers.sql", "Code", "Staging model: 1:1 pass-through of customers with light renaming"),
    ("dbt/models/staging/kinetic/stg_kinetic__subscription_plans.sql", "Code", "Staging model: 1:1 pass-through of subscription_plans"),
    ("dbt/models/staging/kinetic/stg_kinetic__subscriptions.sql", "Code", "Staging model: 1:1 pass-through of subscriptions"),
    ("dbt/models/staging/kinetic/stg_kinetic__invoices.sql", "Code", "Staging model: 1:1 pass-through of invoices"),
    ("dbt/models/staging/kinetic/stg_kinetic__products.sql", "Code", "Staging model: 1:1 pass-through of products"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "not_null/unique/relationships tests for the Phase 1/2 staging models"),
    ("dbt/models/intermediate/int_subscription_paid_periods.sql", "Code", "Intermediate model: resolves each subscription's true paid-start date (trial-vs-paid logic), defined once so every downstream mart agrees"),
    ("dbt/models/intermediate/_intermediate.yml", "Code", "Descriptions and tests for all intermediate models"),
    ("dbt/models/marts/mart_mrr_monthly.sql", "Code", "First canonical metric mart: active subscribers + MRR/ARR by month, validated against a hand-run equivalent query on the live database (2026-07: 90 active subscribers, ~$2,133 MRR)"),
    ("dbt/models/marts/_marts.yml", "Code", "Tests for mart_mrr_monthly"),
    ("dbt/README.md", "Docs", "Updated: what's built so far now includes the Phase 3 storefront staging models + mart_storefront_revenue_monthly"),
    ("dbt/models/staging/kinetic/stg_kinetic__orders.sql", "Code", "Staging model: 1:1 pass-through of orders, plus is_guest_order/has_discount convenience booleans"),
    ("dbt/models/staging/kinetic/stg_kinetic__order_line_items.sql", "Code", "Staging model: 1:1 pass-through of order_line_items"),
    ("dbt/models/staging/kinetic/stg_kinetic__payments.sql", "Code", "Staging model: 1:1 pass-through of payments"),
    ("dbt/models/staging/kinetic/stg_kinetic__refunds.sql", "Code", "Staging model: 1:1 pass-through of refunds"),
    ("dbt/models/staging/kinetic/stg_kinetic__discount_codes.sql", "Code", "Staging model: 1:1 pass-through of discount_codes"),
    ("dbt/models/intermediate/int_orders_refunded.sql", "Code", "Intermediate model: per-order total of succeeded refunds only (failed/pending refunds don't reduce reported revenue)"),
    ("dbt/models/intermediate/int_customer_identity.sql", "Code", "Intermediate model: lookup from every web anonymous_id and account email to its customer (guest emails matched by email; anonymous sessions back-filled; deleted accounts excluded)"),
    ("dbt/models/intermediate/int_orders_net.sql", "Code", "Intermediate model: one row per order with gross (pre-discount), discount, paid, succeeded-refund and net amounts, plus customer_id resolved for guest orders via email match"),
    ("dbt/tests/assert_int_orders_net_no_negative_net.sql", "Code", "dbt test: fails if any order's net is below zero (net is deliberately not floored)"),
    ("dbt/tests/assert_int_orders_net_money_reconciles.sql", "Code", "dbt test: gross - discount = paid and paid - refund = net on every order"),
    ("dbt/tests/assert_int_orders_net_refunds_match_source.sql", "Code", "dbt test: total refunds in int_orders_net equal total succeeded refunds in int_orders_refunded"),
    ("dbt/models/marts/mart_storefront_revenue_monthly.sql", "Code", "Second canonical metric mart: non-subscription (course+merch) gross/net revenue, AOV, guest-checkout share, discount-usage share, refund rate by month -- validated against a hand-run equivalent query on the live database (2026-07: 246 orders, $13,843.71 gross revenue, $56.28 AOV)"),
    ("dbt/models/staging/kinetic/stg_kinetic__customer_addresses.sql", "Code", "Phase 2 staging (Customer 360): 1:1 pass-through of customer_addresses"),
    ("dbt/models/staging/kinetic/stg_kinetic__devices.sql", "Code", "Phase 2 staging (Customer 360): 1:1 pass-through of devices, plus is_anonymous_device flag (customer_id null for ~94% of devices by design)"),
    ("dbt/models/staging/kinetic/stg_kinetic__identity_map.sql", "Code", "Phase 2 staging (Customer 360): 1:1 pass-through of identity_map"),
    ("dbt/models/staging/kinetic/stg_kinetic__segments.sql", "Code", "Phase 2 staging (Customer 360): 1:1 pass-through of segments"),
    ("dbt/models/staging/kinetic/stg_kinetic__customer_segment_membership.sql", "Code", "Phase 2 staging (Customer 360): 1:1 pass-through of customer_segment_membership, plus is_current_member flag"),
    ("dbt/models/staging/kinetic/stg_kinetic__subscription_events.sql", "Code", "Phase 2 staging (Customer 360): 1:1 pass-through of subscription_events; old_plan/new_plan renamed to old_plan_id/new_plan_id"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 6 Customer 360 staging models (PK not_null/unique, FK relationships) -- all hand-verified against live data first"),
    ("dbt/models/staging/kinetic/stg_kinetic__web_sessions.sql", "Code", "Phase 2 staging (web/app engagement): 1:1 pass-through of web_sessions, plus is_known_customer flag (customer_id null for ~79% of sessions by design)"),
    ("dbt/models/staging/kinetic/stg_kinetic__web_events.sql", "Code", "Phase 2 staging (web/app engagement): 1:1 pass-through of web_events"),
    ("dbt/models/staging/kinetic/stg_kinetic__app_sessions.sql", "Code", "Phase 2 staging (web/app engagement): 1:1 pass-through of app_sessions"),
    ("dbt/models/staging/kinetic/stg_kinetic__app_events.sql", "Code", "Phase 2 staging (web/app engagement): 1:1 pass-through of app_events"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 4 web/app engagement staging models -- all hand-verified against live data first"),
    ("dbt/models/staging/kinetic/stg_kinetic__braze_email_campaigns.sql", "Code", "Phase 2 staging (email/push): 1:1 pass-through of braze_email_campaigns"),
    ("dbt/models/staging/kinetic/stg_kinetic__braze_push_campaigns.sql", "Code", "Phase 2 staging (email/push): 1:1 pass-through of braze_push_campaigns"),
    ("dbt/models/staging/kinetic/stg_kinetic__braze_email_events.sql", "Code", "Phase 2 staging (email/push): braze_email_events with external_user_id renamed to customer_id and a short event_name (send/open/click/bounce/unsubscribe) alongside Braze's raw event_type"),
    ("dbt/models/staging/kinetic/stg_kinetic__braze_push_events.sql", "Code", "Phase 2 staging (email/push): braze_push_events with external_user_id renamed to customer_id and a short event_name alongside Braze's raw event_type"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 4 Braze staging models, incl. accepted_values on event_name -- all hand-verified against live data first"),
    ("dbt/models/staging/kinetic/stg_kinetic__meta_campaigns.sql", "Code", "Phase 2 staging (paid media: Meta): meta_campaigns with budgets in both raw cents and dollars (Meta API stores budgets in cents)"),
    ("dbt/models/staging/kinetic/stg_kinetic__meta_ads.sql", "Code", "Phase 2 staging (paid media: Meta): 1:1 pass-through of meta_ads"),
    ("dbt/models/staging/kinetic/stg_kinetic__meta_ad_insights_daily.sql", "Code", "Phase 2 staging (paid media: Meta): meta_ad_insights_daily with a combined ad_day_id key, unit-suffixed columns (spend_usd, cpm_usd, cpc_usd) and ctr renamed ctr_fraction (0.017 = 1.7%)"),
    ("dbt/models/staging/kinetic/stg_kinetic__meta_ad_actions_daily.sql", "Code", "Phase 2 staging (paid media: Meta): meta_ad_actions_daily with a combined ad_day_action_id key; value renamed action_count"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 4 Meta staging models, incl. uniqueness of the combined daily keys -- all hand-verified against live data first"),
    ("dbt/models/staging/kinetic/stg_kinetic__google_search_campaigns.sql", "Code", "Phase 2 staging (paid media: Google Search): campaigns with the raw customer_id renamed google_ads_account_id (it's the Google Ads account number, not a Kinetic customer), daily budget in micros and dollars, end_date cast back to a date"),
    ("dbt/models/staging/kinetic/stg_kinetic__google_search_ad_groups.sql", "Code", "Phase 2 staging (paid media: Google Search): ad groups; cpc_bid_micros cast back to a number (always empty -- automated bidding)"),
    ("dbt/models/staging/kinetic/stg_kinetic__google_search_performance_daily.sql", "Code", "Phase 2 staging (paid media: Google Search): ad-group-day performance with combined ad_group_day_id key, cost converted from micros to dollars, ctr_fraction. The keyword table rolled up -- never add the two together"),
    ("dbt/models/staging/kinetic/stg_kinetic__google_search_keyword_performance_daily.sql", "Code", "Phase 2 staging (paid media: Google Search): keyword-day performance with combined keyword_day_id key, cost converted from micros to dollars, ctr_fraction"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 4 Google Search staging models -- all hand-verified against live data first"),
    ("dbt/models/staging/kinetic/stg_kinetic__youtube_campaigns.sql", "Code", "Phase 2 staging (paid media: YouTube): campaigns with customer_id renamed google_ads_account_id (the ad account, not a Kinetic customer), budgets in micros and dollars"),
    ("dbt/models/staging/kinetic/stg_kinetic__youtube_ad_groups.sql", "Code", "Phase 2 staging (paid media: YouTube): 1:1 pass-through of youtube_ad_groups"),
    ("dbt/models/staging/kinetic/stg_kinetic__youtube_performance_daily.sql", "Code", "Phase 2 staging (paid media: YouTube): ad-group-day performance with combined ad_group_day_id key, cost and cost-per-view converted from micros to dollars, video_view_rate_fraction"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 3 YouTube staging models -- all hand-verified against live data first"),
    ("dbt/models/staging/kinetic/stg_kinetic__dv360_insertion_orders.sql", "Code", "Phase 2 staging (paid media: DV360): insertion orders with budget_micros named monthly_budget_* (it's a monthly budget), end_date cast back to a date; flags the flat-budget-vs-growing-spend known issue"),
    ("dbt/models/staging/kinetic/stg_kinetic__dv360_line_items.sql", "Code", "Phase 2 staging (paid media: DV360): 1:1 pass-through of dv360_line_items"),
    ("dbt/models/staging/kinetic/stg_kinetic__dv360_performance_daily.sql", "Code", "Phase 2 staging (paid media: DV360): line-item x day x exchange x environment performance with combined line_item_day_slice_id key, micros converted to dollars, ctr_fraction"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 3 DV360 staging models, incl. accepted_values on exchange and environment -- all hand-verified against live data first"),
    ("generator/params.py", "Code", "Updated 2026-09-29: every evergreen ad budget on all 6 platforms is now the campaign's CURRENT budget, sized from realized spend (weekly average <= budget, no day > 1.75x; DV360 monthly >= highest month). The old flat 'typical day' budgets let later months spend up to ~20x the stored budget"),
    ("data/meta_campaigns.csv", "Shipped table", "Regenerated 2026-09-29: evergreen daily_budget values updated to current budgets (only that column, only the 4 evergreen rows changed)"),
    ("data/google_search_campaigns.csv", "Shipped table", "Regenerated 2026-09-29: campaign_budget_micros updated to current budgets (only that column changed)"),
    ("data/youtube_campaigns.csv", "Shipped table", "Regenerated 2026-09-29: evergreen campaign_budget_micros updated to current budgets (only that column, only the 4 evergreen rows changed)"),
    ("data/dv360_insertion_orders.csv", "Shipped table", "Regenerated 2026-09-29: monthly budget_micros updated to current budgets (only that column changed)"),
    ("data/snap_campaigns.csv", "Shipped table", "Regenerated 2026-09-29: evergreen daily_budget_micro updated to current budgets (only that column, only the 4 evergreen rows changed)"),
    ("data/tiktok_campaigns.csv", "Shipped table", "Regenerated 2026-09-29: BUDGET_MODE_DAY budget_micro updated to current budgets (only that column, only the 4 evergreen rows changed)"),
    ("generator/audit_cross_dataset_alignment.py", "Code", "Updated 2026-09-29: new Check 8 -- spend vs stored budget for every campaign on all 6 platforms (weekly/daily limits for daily budgets, monthly for DV360, total for holiday flights)"),
    ("dbt/models/staging/kinetic/stg_kinetic__dv360_insertion_orders.sql", "Code", "Updated: budget known-issue note replaced -- budgets are now current budgets"),
    ("generator/paid_media_common.py", "Code", "Updated 2026-09-29: new cap_flight_at_budget() -- rescales a holiday flight's days so it never spends past its lifetime budget, replaying the same random rates so every other row is unchanged"),
    ("generator/build_meta_ad_insights_daily.py", "Code", "Updated 2026-09-29: holiday flights capped at their lifetime budget via cap_flight_at_budget()"),
    ("generator/build_snap_stats_daily.py", "Code", "Updated 2026-09-29: holiday flights capped at their lifetime budget via cap_flight_at_budget()"),
    ("generator/build_tiktok_reports_daily.py", "Code", "Updated 2026-09-29: holiday flights capped at their lifetime budget via cap_flight_at_budget()"),
    ("generator/build_youtube_performance_daily.py", "Code", "Updated 2026-09-29: holiday flights capped at their lifetime budget via cap_flight_at_budget() (no-op today -- all YouTube flights were already under budget)"),
    ("data/meta_ad_insights_daily.csv", "Shipped table", "Regenerated 2026-09-29: the 2023 and 2024 holiday flights (38 rows) trimmed to spend exactly their lifetime budget; every other row identical"),
    ("data/meta_ad_actions_daily.csv", "Shipped table", "Regenerated 2026-09-29: re-derived from the trimmed insights rows -- only the 2023/2024 holiday flights' action rows changed (one initiate_checkout row on 2024-11-15 dropped to zero and is no longer emitted)"),
    ("data/snap_stats_daily.csv", "Shipped table", "Regenerated 2026-09-29: the 2024 holiday flight (19 rows) trimmed to spend exactly its lifetime budget; every other row identical"),
    ("data/tiktok_reports_daily.csv", "Shipped table", "Regenerated 2026-09-29: the 2023/2024/2025 holiday flights (56 rows) trimmed to spend exactly their lifetime budgets; every other row identical"),
    ("docs/cross_dataset_alignment_audit.md", "Docs", "Updated 2026-09-29: added Check 8 (spend vs stored budget) with both fixes and results"),
    ("generator/audit_cross_dataset_alignment.py", "Code", "Updated 2026-09-29: Check 8's flight limit tightened from 1.05x to 1.0x now that flights are capped"),
    ("dbt/models/staging/kinetic/stg_kinetic__snap_campaigns.sql", "Code", "Phase 2 staging (paid media: Snap): campaigns with ad_account_id renamed snap_ad_account_id, current budgets in micros and dollars"),
    ("dbt/models/staging/kinetic/stg_kinetic__snap_ad_squads.sql", "Code", "Phase 2 staging (paid media: Snap): 1:1 pass-through of snap_ad_squads (Snap's ad set / ad group level)"),
    ("dbt/models/staging/kinetic/stg_kinetic__snap_ads.sql", "Code", "Phase 2 staging (paid media: Snap): 1:1 pass-through of snap_ads"),
    ("dbt/models/staging/kinetic/stg_kinetic__snap_stats_daily.sql", "Code", "Phase 2 staging (paid media: Snap): ad-day stats with combined ad_day_id key, spend in micros and dollars; documents swipes as Snap's clicks"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 4 Snap staging models -- all hand-verified against live data first"),
    ("dbt/models/staging/kinetic/stg_kinetic__tiktok_campaigns.sql", "Code", "Phase 2 staging (paid media: TikTok): campaigns with the single budget split into daily_budget_usd / lifetime_budget_usd by budget_mode (matching the other platforms), advertiser_id renamed tiktok_advertiser_id"),
    ("dbt/models/staging/kinetic/stg_kinetic__tiktok_adgroups.sql", "Code", "Phase 2 staging (paid media: TikTok): 1:1 pass-through of tiktok_adgroups"),
    ("dbt/models/staging/kinetic/stg_kinetic__tiktok_ads.sql", "Code", "Phase 2 staging (paid media: TikTok): 1:1 pass-through of tiktok_ads"),
    ("dbt/models/staging/kinetic/stg_kinetic__tiktok_reports_daily.sql", "Code", "Phase 2 staging (paid media: TikTok): ad-day reports with combined ad_day_id key, spend and CPM in micros and dollars, ctr_fraction"),
    ("dbt/models/staging/kinetic/stg_kinetic__product_variants.sql", "Code", "Phase 2 staging (final table, 47 of 47): product variants with variant_option, price_adjustment_usd"),
    ("HANDOFF.md", "Doc", "Handoff note for starting a new chat/project: status, open decisions, prior decisions, pitfalls"),
    ("dbt/models/staging/kinetic/_kinetic__staging.yml", "Code", "Updated: tests for the 4 TikTok staging models -- all hand-verified against live data first"),
]


def last_modified_pacific(rel_path):
    import subprocess
    if rel_path == "File_Manifest.xlsx":
        # Self-referential: this file is about to be overwritten, so use "now"
        # rather than its stale pre-save mtime.
        result = subprocess.run(
            ["date", "+%Y-%m-%d %H:%M %Z"],
            env={**os.environ, "TZ": "America/Los_Angeles"},
            capture_output=True, text=True,
        )
        return result.stdout.strip()
    full_path = os.path.join(PROJECT_ROOT, rel_path)
    ts = os.path.getmtime(full_path)
    result = subprocess.run(
        ["date", "-d", f"@{int(ts)}", "+%Y-%m-%d %H:%M %Z"],
        env={**os.environ, "TZ": "America/Los_Angeles"},
        capture_output=True, text=True,
    )
    return result.stdout.strip()


def build():
    wb = Workbook()
    ws = wb.active
    ws.title = "File Manifest"

    headers = ["File Path", "Category", "Description", "Last Updated (Pacific)"]
    ws.append(headers)
    for col, _ in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col)
        cell.font = Font(name="Arial", bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="2A6F6F")
        cell.alignment = Alignment(vertical="center")

    for rel_path, category, description in FILES:
        timestamp = last_modified_pacific(rel_path)
        ws.append([rel_path, category, description, timestamp])

    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.font = Font(name="Arial")
            cell.alignment = Alignment(vertical="center", wrap_text=(cell.column == 3))

    widths = {1: 48, 2: 16, 3: 60, 4: 22}
    for col, width in widths.items():
        ws.column_dimensions[get_column_letter(col)].width = width

    ws.freeze_panes = "A2"
    wb.save(OUTPUT_PATH)
    print(f"Wrote {OUTPUT_PATH} with {len(FILES)} file rows")


if __name__ == "__main__":
    build()
